export const COMMENTS = [
  {
    id: 0,
    serviceId: 0,
    rating: 5,
    text: "alfjadsl fadslfj asdlfj asdlfj ald;sjfladjf ldfuien gakl;hngaohg.",
    author: "Simon Hunt",
    date: "2018-10-25T16:30Z",
  },
  {
    id: 1,
    serviceId: 0,
    rating: 3,
    text: "alfjadsl fadslfj asdlfj asdlfj ald;sjfladjf ldfuien gakl;hngaohg.",
    author: "Zandra Katherine",
    date: "2017-06-17T03:33Z",
  },
  {
    id: 2,
    serviceId: 0,
    rating: 4,
    text: "alfjadsl fadslfj asdlfj asdlfj ald;sjfladjf ldfuien gakl;hngaohg.",
    author: "Amy Keophilavong",
    date: "2019-02-18T18:12Z",
  },
  {
    id: 3,
    serviceId: 0,
    rating: 3,
    text: "alfjadsl fadslfj asdlfj asdlfj ald;sjfladjf ldfuien gakl;hngaohg.",
    author: "Jean Luc",
    date: "2019-08-04T20:11Z",
  },
  {
    id: 4,
    serviceId: 0,
    rating: 5,
    text: "alfjadsl fadslfj asdlfj asdlfj ald;sjfladjf ldfuien gakl;hngaohg.",
    author: "R. E. Osariemen",
    date: "2018-07-23T19:44Z",
  },
  {
    id: 5,
    serviceId: 1,
    rating: 4,
    text: "alfjadsl fadslfj asdlfj asdlfj ald;sjfladjf ldfuien gakl;hngaohg.",
    author: "Juan Cortez",
    date: "2017-06-17T03:33Z",
  },
  {
    id: 6,
    serviceId: 1,
    rating: 5,
    text: "alfjadsl fadslfj asdlfj asdlfj ald;sjfladjf ldfuien gakl;hngaohg.",
    author: "McKenzie Sebastian",
    date: "2019-02-18T18:12Z",
  },
  {
    id: 7,
    serviceId: 1,
    rating: 5,
    text: "alfjadsl fadslfj asdlfj asdlfj ald;sjfladjf ldfuien gakl;hngaohg.",
    author: "Brennen Ech",
    date: "2019-08-04T20:11Z",
  },
  {
    id: 8,
    serviceId: 1,
    rating: 4,
    text: "alfjadsl fadslfj asdlfj asdlfj ald;sjfladjf ldfuien gakl;hngaohg.",
    author: "Amy Keophilavong",
    date: "2018-07-23T19:44Z",
  },
  {
    id: 9,
    serviceId: 1,
    rating: 5,
    text: "alfjadsl fadslfj asdlfj asdlfj ald;sjfladjf ldfuien gakl;hngaohg.",
    author: "Jordan Runn",
    date: "2019-08-04T20:11Z",
  },
  {
    id: 10,
    serviceId: 2,
    rating: 5,
    text: "alfjadsl fadslfj asdlfj asdlfj ald;sjfladjf ldfuien gakl;hngaohg.",
    author: "Olaf the Snowman",
    date: "2019-02-18T18:12Z",
  },
  {
    id: 11,
    campsiteId: 2,
    rating: 1,
    text: "alfjadsl fadslfj asdlfj asdlfj ald;sjfladjf ldfuien gakl;hngaohg.",
    author: "Vincent and Mona Lisa Gambini",
    date: "2018-10-25T16:30Z",
  },
  {
    id: 12,
    campsiteId: 2,
    rating: 5,
    text: "alfjadsl fadslfj asdlfj asdlfj ald;sjfladjf ldfuien gakl;hngaohg.",
    author: "Ann Dabramov",
    date: "2018-07-23T19:44Z",
  },
  {
    id: 13,
    campsiteId: 2,
    rating: 4,
    text: "alfjadsl fadslfj asdlfj asdlfj ald;sjfladjf ldfuien gakl;hngaohg.",
    author: "Amy Keophilavong",
    date: "2018-10-25T16:30Z",
  },
  {
    id: 14,
    campsiteId: 2,
    rating: 5,
    text: "alfjadsl fadslfj asdlfj asdlfj ald;sjfladjf ldfuien gakl;hngaohg.",
    author: "Dave Lister",
    date: "2019-08-04T20:11Z",
  },
  {
    id: 15,
    campsiteId: 3,
    rating: 4,
    text: "alfjadsl fadslfj asdlfj asdlfj ald;sjfladjf ldfuien gakl;hngaohg.",
    author: "Markell Richards",
    date: "2017-06-17T03:33Z",
  },
  {
    id: 16,
    campsiteId: 3,
    rating: 5,
    text: "alfjadsl fadslfj asdlfj asdlfj ald;sjfladjf ldfuien gakl;hngaohg.",
    author: "Amy Keophilavong",
    date: "2018-07-23T19:44Z",
  },
  {
    id: 17,
    campsiteId: 3,
    rating: 5,
    text: "alfjadsl fadslfj asdlfj asdlfj ald;sjfladjf ldfuien gakl;hngaohg.",
    author: "Tinus Lorvaldes",
    date: "2018-10-25T16:30Z",
  },
  {
    id: 18,
    campsiteId: 3,
    rating: 4,
    text: "alfjadsl fadslfj asdlfj asdlfj ald;sjfladjf ldfuien gakl;hngaohg.",
    author: "Chloe Haskins",
    date: "2017-06-17T03:33Z",
  },
  {
    id: 19,
    campsiteId: 3,
    rating: 5,
    text: "alfjadsl fadslfj asdlfj asdlfj ald;sjfladjf ldfuien gakl;hngaohg.",
    author: "Minae Lee",
    date: "2019-02-18T18:12Z",
  },
];
